# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ai_server_pb2 as ai__server__pb2


class OCRStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnUpdateStep = channel.unary_unary(
                '/ai_server.OCR/OnUpdateStep',
                request_serializer=ai__server__pb2.SendStep.SerializeToString,
                response_deserializer=ai__server__pb2.ReplySendStep.FromString,
                )
        self.OnComplete = channel.unary_unary(
                '/ai_server.OCR/OnComplete',
                request_serializer=ai__server__pb2.SendResult.SerializeToString,
                response_deserializer=ai__server__pb2.ReplySendResult.FromString,
                )
        self.Start = channel.unary_unary(
                '/ai_server.OCR/Start',
                request_serializer=ai__server__pb2.RequestStart.SerializeToString,
                response_deserializer=ai__server__pb2.ReplyRequestStart.FromString,
                )


class OCRServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnUpdateStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OCRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnUpdateStep': grpc.unary_unary_rpc_method_handler(
                    servicer.OnUpdateStep,
                    request_deserializer=ai__server__pb2.SendStep.FromString,
                    response_serializer=ai__server__pb2.ReplySendStep.SerializeToString,
            ),
            'OnComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.OnComplete,
                    request_deserializer=ai__server__pb2.SendResult.FromString,
                    response_serializer=ai__server__pb2.ReplySendResult.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=ai__server__pb2.RequestStart.FromString,
                    response_serializer=ai__server__pb2.ReplyRequestStart.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_server.OCR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OCR(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnUpdateStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_server.OCR/OnUpdateStep',
            ai__server__pb2.SendStep.SerializeToString,
            ai__server__pb2.ReplySendStep.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_server.OCR/OnComplete',
            ai__server__pb2.SendResult.SerializeToString,
            ai__server__pb2.ReplySendResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_server.OCR/Start',
            ai__server__pb2.RequestStart.SerializeToString,
            ai__server__pb2.ReplyRequestStart.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class StyleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnUpdateStep = channel.unary_unary(
                '/ai_server.Style/OnUpdateStep',
                request_serializer=ai__server__pb2.SendStep.SerializeToString,
                response_deserializer=ai__server__pb2.ReplySendStep.FromString,
                )
        self.OnComplete = channel.unary_unary(
                '/ai_server.Style/OnComplete',
                request_serializer=ai__server__pb2.SendResult.SerializeToString,
                response_deserializer=ai__server__pb2.ReplySendResult.FromString,
                )
        self.Start = channel.unary_unary(
                '/ai_server.Style/Start',
                request_serializer=ai__server__pb2.RequestStart.SerializeToString,
                response_deserializer=ai__server__pb2.ReplyRequestStart.FromString,
                )


class StyleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnUpdateStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StyleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnUpdateStep': grpc.unary_unary_rpc_method_handler(
                    servicer.OnUpdateStep,
                    request_deserializer=ai__server__pb2.SendStep.FromString,
                    response_serializer=ai__server__pb2.ReplySendStep.SerializeToString,
            ),
            'OnComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.OnComplete,
                    request_deserializer=ai__server__pb2.SendResult.FromString,
                    response_serializer=ai__server__pb2.ReplySendResult.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=ai__server__pb2.RequestStart.FromString,
                    response_serializer=ai__server__pb2.ReplyRequestStart.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_server.Style', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Style(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnUpdateStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_server.Style/OnUpdateStep',
            ai__server__pb2.SendStep.SerializeToString,
            ai__server__pb2.ReplySendStep.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_server.Style/OnComplete',
            ai__server__pb2.SendResult.SerializeToString,
            ai__server__pb2.ReplySendResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_server.Style/Start',
            ai__server__pb2.RequestStart.SerializeToString,
            ai__server__pb2.ReplyRequestStart.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
