# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ai_server.proto',
  package='ai_server',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61i_server.proto\x12\tai_server\"(\n\x08SendStep\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x0c\n\x04step\x18\x02 \x01(\x05\"B\n\rReplySendStep\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x0c\n\x04step\x18\x02 \x01(\x05\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\"*\n\nSendResult\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"6\n\x0fReplySendResult\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"\x1e\n\x0cRequestStart\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\"8\n\x11ReplyRequestStart\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x32\xcb\x01\n\x03OCR\x12?\n\x0cOnUpdateStep\x12\x13.ai_server.SendStep\x1a\x18.ai_server.ReplySendStep\"\x00\x12\x41\n\nOnComplete\x12\x15.ai_server.SendResult\x1a\x1a.ai_server.ReplySendResult\"\x00\x12@\n\x05Start\x12\x17.ai_server.RequestStart\x1a\x1c.ai_server.ReplyRequestStart\"\x00\x32\xcd\x01\n\x05Style\x12?\n\x0cOnUpdateStep\x12\x13.ai_server.SendStep\x1a\x18.ai_server.ReplySendStep\"\x00\x12\x41\n\nOnComplete\x12\x15.ai_server.SendResult\x1a\x1a.ai_server.ReplySendResult\"\x00\x12@\n\x05Start\x12\x17.ai_server.RequestStart\x1a\x1c.ai_server.ReplyRequestStart\"\x00\x62\x06proto3'
)




_SENDSTEP = _descriptor.Descriptor(
  name='SendStep',
  full_name='ai_server.SendStep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.SendStep.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='ai_server.SendStep.step', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=70,
)


_REPLYSENDSTEP = _descriptor.Descriptor(
  name='ReplySendStep',
  full_name='ai_server.ReplySendStep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.ReplySendStep.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='ai_server.ReplySendStep.step', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='ai_server.ReplySendStep.status_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=138,
)


_SENDRESULT = _descriptor.Descriptor(
  name='SendResult',
  full_name='ai_server.SendResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.SendResult.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ai_server.SendResult.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=182,
)


_REPLYSENDRESULT = _descriptor.Descriptor(
  name='ReplySendResult',
  full_name='ai_server.ReplySendResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.ReplySendResult.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='ai_server.ReplySendResult.status_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=238,
)


_REQUESTSTART = _descriptor.Descriptor(
  name='RequestStart',
  full_name='ai_server.RequestStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.RequestStart.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=270,
)


_REPLYREQUESTSTART = _descriptor.Descriptor(
  name='ReplyRequestStart',
  full_name='ai_server.ReplyRequestStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.ReplyRequestStart.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='ai_server.ReplyRequestStart.status_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=328,
)

DESCRIPTOR.message_types_by_name['SendStep'] = _SENDSTEP
DESCRIPTOR.message_types_by_name['ReplySendStep'] = _REPLYSENDSTEP
DESCRIPTOR.message_types_by_name['SendResult'] = _SENDRESULT
DESCRIPTOR.message_types_by_name['ReplySendResult'] = _REPLYSENDRESULT
DESCRIPTOR.message_types_by_name['RequestStart'] = _REQUESTSTART
DESCRIPTOR.message_types_by_name['ReplyRequestStart'] = _REPLYREQUESTSTART
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendStep = _reflection.GeneratedProtocolMessageType('SendStep', (_message.Message,), {
  'DESCRIPTOR' : _SENDSTEP,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.SendStep)
  })
_sym_db.RegisterMessage(SendStep)

ReplySendStep = _reflection.GeneratedProtocolMessageType('ReplySendStep', (_message.Message,), {
  'DESCRIPTOR' : _REPLYSENDSTEP,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.ReplySendStep)
  })
_sym_db.RegisterMessage(ReplySendStep)

SendResult = _reflection.GeneratedProtocolMessageType('SendResult', (_message.Message,), {
  'DESCRIPTOR' : _SENDRESULT,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.SendResult)
  })
_sym_db.RegisterMessage(SendResult)

ReplySendResult = _reflection.GeneratedProtocolMessageType('ReplySendResult', (_message.Message,), {
  'DESCRIPTOR' : _REPLYSENDRESULT,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.ReplySendResult)
  })
_sym_db.RegisterMessage(ReplySendResult)

RequestStart = _reflection.GeneratedProtocolMessageType('RequestStart', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSTART,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.RequestStart)
  })
_sym_db.RegisterMessage(RequestStart)

ReplyRequestStart = _reflection.GeneratedProtocolMessageType('ReplyRequestStart', (_message.Message,), {
  'DESCRIPTOR' : _REPLYREQUESTSTART,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.ReplyRequestStart)
  })
_sym_db.RegisterMessage(ReplyRequestStart)



_OCR = _descriptor.ServiceDescriptor(
  name='OCR',
  full_name='ai_server.OCR',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=331,
  serialized_end=534,
  methods=[
  _descriptor.MethodDescriptor(
    name='OnUpdateStep',
    full_name='ai_server.OCR.OnUpdateStep',
    index=0,
    containing_service=None,
    input_type=_SENDSTEP,
    output_type=_REPLYSENDSTEP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OnComplete',
    full_name='ai_server.OCR.OnComplete',
    index=1,
    containing_service=None,
    input_type=_SENDRESULT,
    output_type=_REPLYSENDRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='ai_server.OCR.Start',
    index=2,
    containing_service=None,
    input_type=_REQUESTSTART,
    output_type=_REPLYREQUESTSTART,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCR)

DESCRIPTOR.services_by_name['OCR'] = _OCR


_STYLE = _descriptor.ServiceDescriptor(
  name='Style',
  full_name='ai_server.Style',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=537,
  serialized_end=742,
  methods=[
  _descriptor.MethodDescriptor(
    name='OnUpdateStep',
    full_name='ai_server.Style.OnUpdateStep',
    index=0,
    containing_service=None,
    input_type=_SENDSTEP,
    output_type=_REPLYSENDSTEP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OnComplete',
    full_name='ai_server.Style.OnComplete',
    index=1,
    containing_service=None,
    input_type=_SENDRESULT,
    output_type=_REPLYSENDRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='ai_server.Style.Start',
    index=2,
    containing_service=None,
    input_type=_REQUESTSTART,
    output_type=_REPLYREQUESTSTART,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STYLE)

DESCRIPTOR.services_by_name['Style'] = _STYLE

# @@protoc_insertion_point(module_scope)
