# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ai_server.proto',
  package='ai_server',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61i_server.proto\x12\tai_server\",\n\x0cSendProgress\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x0c\n\x04step\x18\x02 \x01(\x05\"7\n\x10ReplyGetProgress\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"*\n\nSendResult\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"5\n\x0eReplyGetResult\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"!\n\x0fRequestRunModel\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\"4\n\rReplyRunModel\x12\x0e\n\x06req_id\x18\x01 \x01(\x03\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x32\xd1\x01\n\x03OCR\x12\x45\n\x0bGetProgress\x12\x17.ai_server.SendProgress\x1a\x1b.ai_server.ReplyGetProgress\"\x00\x12?\n\tGetResult\x12\x15.ai_server.SendResult\x1a\x19.ai_server.ReplyGetResult\"\x00\x12\x42\n\x08RunModel\x12\x1a.ai_server.RequestRunModel\x1a\x18.ai_server.ReplyRunModel\"\x00\x32\xd3\x01\n\x05Style\x12\x45\n\x0bGetProgress\x12\x17.ai_server.SendProgress\x1a\x1b.ai_server.ReplyGetProgress\"\x00\x12?\n\tGetResult\x12\x15.ai_server.SendResult\x1a\x19.ai_server.ReplyGetResult\"\x00\x12\x42\n\x08RunModel\x12\x1a.ai_server.RequestRunModel\x1a\x18.ai_server.ReplyRunModel\"\x00\x62\x06proto3'
)




_SENDPROGRESS = _descriptor.Descriptor(
  name='SendProgress',
  full_name='ai_server.SendProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.SendProgress.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='ai_server.SendProgress.step', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=74,
)


_REPLYGETPROGRESS = _descriptor.Descriptor(
  name='ReplyGetProgress',
  full_name='ai_server.ReplyGetProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.ReplyGetProgress.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='ai_server.ReplyGetProgress.status_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=131,
)


_SENDRESULT = _descriptor.Descriptor(
  name='SendResult',
  full_name='ai_server.SendResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.SendResult.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ai_server.SendResult.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=175,
)


_REPLYGETRESULT = _descriptor.Descriptor(
  name='ReplyGetResult',
  full_name='ai_server.ReplyGetResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.ReplyGetResult.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='ai_server.ReplyGetResult.status_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=230,
)


_REQUESTRUNMODEL = _descriptor.Descriptor(
  name='RequestRunModel',
  full_name='ai_server.RequestRunModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.RequestRunModel.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=265,
)


_REPLYRUNMODEL = _descriptor.Descriptor(
  name='ReplyRunModel',
  full_name='ai_server.ReplyRunModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='ai_server.ReplyRunModel.req_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='ai_server.ReplyRunModel.status_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=319,
)

DESCRIPTOR.message_types_by_name['SendProgress'] = _SENDPROGRESS
DESCRIPTOR.message_types_by_name['ReplyGetProgress'] = _REPLYGETPROGRESS
DESCRIPTOR.message_types_by_name['SendResult'] = _SENDRESULT
DESCRIPTOR.message_types_by_name['ReplyGetResult'] = _REPLYGETRESULT
DESCRIPTOR.message_types_by_name['RequestRunModel'] = _REQUESTRUNMODEL
DESCRIPTOR.message_types_by_name['ReplyRunModel'] = _REPLYRUNMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendProgress = _reflection.GeneratedProtocolMessageType('SendProgress', (_message.Message,), {
  'DESCRIPTOR' : _SENDPROGRESS,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.SendProgress)
  })
_sym_db.RegisterMessage(SendProgress)

ReplyGetProgress = _reflection.GeneratedProtocolMessageType('ReplyGetProgress', (_message.Message,), {
  'DESCRIPTOR' : _REPLYGETPROGRESS,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.ReplyGetProgress)
  })
_sym_db.RegisterMessage(ReplyGetProgress)

SendResult = _reflection.GeneratedProtocolMessageType('SendResult', (_message.Message,), {
  'DESCRIPTOR' : _SENDRESULT,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.SendResult)
  })
_sym_db.RegisterMessage(SendResult)

ReplyGetResult = _reflection.GeneratedProtocolMessageType('ReplyGetResult', (_message.Message,), {
  'DESCRIPTOR' : _REPLYGETRESULT,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.ReplyGetResult)
  })
_sym_db.RegisterMessage(ReplyGetResult)

RequestRunModel = _reflection.GeneratedProtocolMessageType('RequestRunModel', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTRUNMODEL,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.RequestRunModel)
  })
_sym_db.RegisterMessage(RequestRunModel)

ReplyRunModel = _reflection.GeneratedProtocolMessageType('ReplyRunModel', (_message.Message,), {
  'DESCRIPTOR' : _REPLYRUNMODEL,
  '__module__' : 'ai_server_pb2'
  # @@protoc_insertion_point(class_scope:ai_server.ReplyRunModel)
  })
_sym_db.RegisterMessage(ReplyRunModel)



_OCR = _descriptor.ServiceDescriptor(
  name='OCR',
  full_name='ai_server.OCR',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=322,
  serialized_end=531,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProgress',
    full_name='ai_server.OCR.GetProgress',
    index=0,
    containing_service=None,
    input_type=_SENDPROGRESS,
    output_type=_REPLYGETPROGRESS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetResult',
    full_name='ai_server.OCR.GetResult',
    index=1,
    containing_service=None,
    input_type=_SENDRESULT,
    output_type=_REPLYGETRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RunModel',
    full_name='ai_server.OCR.RunModel',
    index=2,
    containing_service=None,
    input_type=_REQUESTRUNMODEL,
    output_type=_REPLYRUNMODEL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCR)

DESCRIPTOR.services_by_name['OCR'] = _OCR


_STYLE = _descriptor.ServiceDescriptor(
  name='Style',
  full_name='ai_server.Style',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=534,
  serialized_end=745,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProgress',
    full_name='ai_server.Style.GetProgress',
    index=0,
    containing_service=None,
    input_type=_SENDPROGRESS,
    output_type=_REPLYGETPROGRESS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetResult',
    full_name='ai_server.Style.GetResult',
    index=1,
    containing_service=None,
    input_type=_SENDRESULT,
    output_type=_REPLYGETRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RunModel',
    full_name='ai_server.Style.RunModel',
    index=2,
    containing_service=None,
    input_type=_REQUESTRUNMODEL,
    output_type=_REPLYRUNMODEL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STYLE)

DESCRIPTOR.services_by_name['Style'] = _STYLE

# @@protoc_insertion_point(module_scope)
