#docker build -t swm_back .
FROM node:16-alpine

WORKDIR /usr/src

# ARG NODE_ENV
# ENV NODE_ENV $NODE_ENV

COPY package*.json /usr/src/
RUN yarn install

ENV PORT 3000
EXPOSE $PORT
CMD [ "npm", "run", "release" ]
#docker run --net=host -d --name swm_back -v $PWD:/usr/src/ swm_back
