#docker build -t swm_back . -f Dockerfile.beta
FROM node:16-alpine

WORKDIR /usr/src

# ARG NODE_ENV
# ENV NODE_ENV $NODE_ENV

COPY package*.json /usr/src/
RUN yarn install

ENV PORT 3000
EXPOSE $PORT
CMD [ "npx", "kill-port", "3000\\", "npm", "run", "release" ]
#docker run  --restart=always --net=host -d --name swm_back -v $PWD:/usr/src/ swm_back
